// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by deepcopy-gen. Do not edit it manually!

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"
	api_v1 "k8s.io/client-go/pkg/api/v1"
	reflect "reflect"
)

func init() {
	SchemeBuilder.Register(RegisterDeepCopies)
}

// RegisterDeepCopies adds deep-copy functions to the given scheme. Public
// to allow building arbitrary schemes.
func RegisterDeepCopies(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedDeepCopyFuncs(
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeClass, InType: reflect.TypeOf(&NodeClass{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeClassList, InType: reflect.TypeOf(&NodeClassList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeClassResource, InType: reflect.TypeOf(&NodeClassResource{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeSet, InType: reflect.TypeOf(&NodeSet{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeSetCondition, InType: reflect.TypeOf(&NodeSetCondition{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeSetList, InType: reflect.TypeOf(&NodeSetList{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeSetSpec, InType: reflect.TypeOf(&NodeSetSpec{})},
		conversion.GeneratedDeepCopyFunc{Fn: DeepCopy_v1alpha1_NodeSetStatus, InType: reflect.TypeOf(&NodeSetStatus{})},
	)
}

func DeepCopy_v1alpha1_NodeClass(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeClass)
		out := out.(*NodeClass)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		if newVal, err := c.DeepCopy(&in.Config); err != nil {
			return err
		} else {
			out.Config = *newVal.(*runtime.RawExtension)
		}
		if in.Resources != nil {
			in, out := &in.Resources, &out.Resources
			*out = make([]NodeClassResource, len(*in))
			for i := range *in {
				if err := DeepCopy_v1alpha1_NodeClassResource(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeClassList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeClassList)
		out := out.(*NodeClassList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]NodeClass, len(*in))
			for i := range *in {
				if err := DeepCopy_v1alpha1_NodeClass(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeClassResource(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeClassResource)
		out := out.(*NodeClassResource)
		*out = *in
		if in.Reference != nil {
			in, out := &in.Reference, &out.Reference
			*out = new(api_v1.ObjectReference)
			**out = **in
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeSet(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeSet)
		out := out.(*NodeSet)
		*out = *in
		if newVal, err := c.DeepCopy(&in.ObjectMeta); err != nil {
			return err
		} else {
			out.ObjectMeta = *newVal.(*v1.ObjectMeta)
		}
		if err := DeepCopy_v1alpha1_NodeSetSpec(&in.Spec, &out.Spec, c); err != nil {
			return err
		}
		if err := DeepCopy_v1alpha1_NodeSetStatus(&in.Status, &out.Status, c); err != nil {
			return err
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeSetCondition(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeSetCondition)
		out := out.(*NodeSetCondition)
		*out = *in
		out.LastTransitionTime = in.LastTransitionTime.DeepCopy()
		return nil
	}
}

func DeepCopy_v1alpha1_NodeSetList(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeSetList)
		out := out.(*NodeSetList)
		*out = *in
		if in.Items != nil {
			in, out := &in.Items, &out.Items
			*out = make([]NodeSet, len(*in))
			for i := range *in {
				if err := DeepCopy_v1alpha1_NodeSet(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeSetSpec(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeSetSpec)
		out := out.(*NodeSetSpec)
		*out = *in
		if in.NodeSelector != nil {
			in, out := &in.NodeSelector, &out.NodeSelector
			*out = make(map[string]string)
			for key, val := range *in {
				(*out)[key] = val
			}
		}
		if in.MaxUnavailable != nil {
			in, out := &in.MaxUnavailable, &out.MaxUnavailable
			*out = new(intstr.IntOrString)
			**out = **in
		}
		if in.MaxSurge != nil {
			in, out := &in.MaxSurge, &out.MaxSurge
			*out = new(intstr.IntOrString)
			**out = **in
		}
		if newVal, err := c.DeepCopy(&in.Config); err != nil {
			return err
		} else {
			out.Config = *newVal.(*runtime.RawExtension)
		}
		return nil
	}
}

func DeepCopy_v1alpha1_NodeSetStatus(in interface{}, out interface{}, c *conversion.Cloner) error {
	{
		in := in.(*NodeSetStatus)
		out := out.(*NodeSetStatus)
		*out = *in
		if in.Conditions != nil {
			in, out := &in.Conditions, &out.Conditions
			*out = make([]NodeSetCondition, len(*in))
			for i := range *in {
				if err := DeepCopy_v1alpha1_NodeSetCondition(&(*in)[i], &(*out)[i], c); err != nil {
					return err
				}
			}
		}
		return nil
	}
}
